# Generated by Django 5.1.5 on 2025-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
    ]
